### ISSUE TITLE
Rectificacion de la referencia de tension del ADC.

### ISSUE THREAD

**Issue by Jmusotoku** [MSTKMAD/MK2#10]
**TARADO DE FONDO DE ESCALA**
Los divisores de tensión para las medidas del ADC están taradas a 3v mientras que la referencia de tensión es de 2.5.

**SOLUCION**:
Cambiar la referencia de  tensión a un modelo de 3v.

**R57 ERRONEA**
Durante las pruebas de test de la versión 1 de la placa, se descubrió que el valor de R57, 800R, no es un valor estándar y debido a eso se monto una resistencia de 10K que impedía el correcto funcionamiento de la referencia de tensión.

**SOLUCION**:
Cambiar el valor a 1k, un valor estandar y que permite el correcto funcionamiento de la referencia (150uA min para el ADC + 45uA de la referencia)
Aunque es suficiente una corriente de 200uA vamos a calcular R57 para  1mA
Ahora, al ser la referencia de 3v en vez de 2.5v, hay que recalcular R57.
(3.3-3v)/1mA = aprox 330R

**Comment by david-reo** [comment]
Hay que cambiar tambien las referencias al valor anterior de 2.5V

![image](https://github.com/MSTKMAD/MK2/assets/103424798/c36a1f15-74ee-4f4d-88d6-8e4bdd30aa1a)
